# Generated by Django 4.0.4 on 2022-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_5', '0002_rename_person_cities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='first_name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='last_name',
            new_name='humidity',
        ),
        migrations.AddField(
            model_name='cities',
            name='temperature',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cities',
            name='weather',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
