# Generated by Django 4.0.4 on 2022-05-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_5', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Cities',
        ),
    ]
